### ISSUE TITLE
Need help running app

### ISSUE THREAD

**Issue by foocross** [Jarhead20/RRPathGen#1]
We want to test the app- but are having problems using it.  When we start with:
java -jar ~/Downloads/RRPathGen-1.1.0.jar

We get a black screen that asks for:
Name:
X:
Y:
Heading:
Type:
Code:
Scale:
Robot Width:

We are not sure what to put for these values.

Any help would be appreciated.

**Comment by Jarhead20** [comment]
This is a known issue, currently the only way is to go into display
settings and change the scaling of apps, you might find it set to 150%, try
changing it to 100%. This might be fixed in the next release, I’ll need to
do more testing.

-Jared

**Comment by Jarhead20** [comment]
Actually since you can see the scale, try setting it to 4 or 6

**Comment by foocross** [comment]
Ok I think it got it.  I had to fist change the scale to 1 then 4.  
Thanks for the help.
