### ISSUE TITLE
Readme image asset

### ISSUE THREAD

**Issue by bubner** [Jarhead20/RRPathGen#26]
Hi,

GitHub had a bit of a hissy fit with the readme image asset, here's the image that was in there.
![rrpathgen](https://github.com/user-attachments/assets/46995097-fe15-4481-8c83-7d20d6bfb980)

**Comment by Jarhead20** [comment]
Fixed in https://github.com/Jarhead20/RRPathGen/commit/f69c2da5d11b4d2d7c6841aae2d4c09cc12bb57d
